import { Seat, Tier } from "../Seat/Types";

export const seat: Seat[] = [
  // 1

  {
    seatId: 1,
    label: "1",
    rowLabel: "A",
    visible: false,
    tierId: 0,
  },
  { seatId: 2, label: "2", rowLabel: "A", visible: false, tierId: 0 },
  { seatId: 3, label: "3", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 4, label: "4", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 5, label: "5", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 6, label: "6", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 7, label: "7", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 8, label: "8", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 9, label: "9", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 10, label: "10", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 11, label: "11", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 12, label: "12", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 13, label: "13", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 14, label: "14", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 15, label: "15", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 16, label: "16", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 17, label: "17", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 18, label: "18", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 19, label: "19", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 20, label: "20", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 21, label: "21", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 22, label: "22", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 23, label: "23", rowLabel: "A", visible: true, tierId: 0 },
  { seatId: 24, label: "24", rowLabel: "A", visible: false, tierId: 0 },
  { seatId: 25, label: "25", rowLabel: "A", visible: false, tierId: 0 },
  {
    seatId: 1010,
    label: "A",
    rowLabel: "A",
    visible: true,
    tierId: 0,
  },
  // 2

  { seatId: 26, label: "1", rowLabel: "B", visible: false, tierId: 0 },
  { seatId: 27, label: "2", rowLabel: "B", visible: false, tierId: 0 },
  { seatId: 28, label: "3", rowLabel: "B", visible: false, tierId: 0 },
  { seatId: 29, label: "4", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 30, label: "5", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 31, label: "6", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 32, label: "7", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 33, label: "8", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 34, label: "9", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 35, label: "10", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 36, label: "11", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 37, label: "12", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 38, label: "13", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 39, label: "14", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 40, label: "15", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 41, label: "16", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 42, label: "17", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 43, label: "18", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 44, label: "19", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 45, label: "20", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 46, label: "21", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 47, label: "22", rowLabel: "B", visible: true, tierId: 0 },
  { seatId: 48, label: "23", rowLabel: "B", visible: false, tierId: 0 },
  { seatId: 49, label: "24", rowLabel: "B", visible: false, tierId: 0 },
  { seatId: 50, label: "25", rowLabel: "B", visible: false, tierId: 0 },
  {
    seatId: 1009,
    label: "B",
    rowLabel: "B",
    visible: true,
    tierId: 0,
  },
  //   3

  { seatId: 51, label: "1", rowLabel: "C", visible: false, tierId: 0 },
  { seatId: 52, label: "2", rowLabel: "C", visible: false, tierId: 0 },
  { seatId: 53, label: "3", rowLabel: "C", visible: false, tierId: 0 },
  { seatId: 54, label: "4", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 55, label: "5", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 56, label: "6", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 57, label: "7", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 58, label: "8", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 59, label: "9", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 60, label: "10", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 61, label: "11", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 62, label: "12", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 63, label: "13", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 64, label: "14", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 65, label: "15", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 66, label: "16", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 67, label: "17", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 68, label: "18", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 69, label: "19", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 70, label: "20", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 71, label: "21", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 72, label: "22", rowLabel: "C", visible: true, tierId: 0 },
  { seatId: 73, label: "23", rowLabel: "C", visible: false, tierId: 0 },
  { seatId: 74, label: "24", rowLabel: "C", visible: false, tierId: 0 },
  { seatId: 75, label: "25", rowLabel: "C", visible: false, tierId: 0 },
  {
    seatId: 1008,
    label: "C",
    rowLabel: "C",
    visible: true,
    tierId: 0,
  },
  // break ---
  { seatId: -49, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -48, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -47, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -46, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -45, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -44, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -43, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -42, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -41, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -40, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -39, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -38, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -37, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -36, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -35, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -34, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -33, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -32, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -31, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -30, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -29, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -28, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -27, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -26, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -25, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  { seatId: -50, label: "-", rowLabel: "C", visible: true, tierId: -1 },
  //   4

  { seatId: 76, label: "1", rowLabel: "D", visible: false, tierId: 1 },
  { seatId: 77, label: "2", rowLabel: "D", visible: false, tierId: 1 },
  { seatId: 78, label: "3", rowLabel: "D", visible: false, tierId: 1 },
  { seatId: 79, label: "4", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 80, label: "5", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 81, label: "6", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 82, label: "7", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 83, label: "8", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 84, label: "9", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 85, label: "10", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 86, label: "11", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 87, label: "12", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 88, label: "13", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 89, label: "14", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 90, label: "15", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 91, label: "16", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 92, label: "17", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 93, label: "18", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 94, label: "19", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 95, label: "20", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 96, label: "21", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 97, label: "22", rowLabel: "D", visible: true, tierId: 1 },
  { seatId: 98, label: "23", rowLabel: "D", visible: false, tierId: 1 },
  { seatId: 99, label: "24", rowLabel: "D", visible: false, tierId: 1 },
  { seatId: 100, label: "25", rowLabel: "D", visible: false, tierId: 1 },
  {
    seatId: 1007,
    label: "D",
    rowLabel: "D",
    visible: true,
    tierId: 0,
  },
  //   5

  { seatId: 101, label: "1", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 102, label: "2", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 103, label: "3", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 104, label: "4", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 105, label: "5", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 106, label: "6", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 107, label: "7", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 108, label: "8", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 109, label: "9", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 110, label: "10", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 111, label: "11", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 112, label: "12", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 113, label: "13", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 114, label: "14", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 115, label: "15", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 116, label: "16", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 117, label: "17", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 118, label: "18", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 119, label: "19", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 120, label: "20", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 121, label: "21", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 122, label: "22", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 123, label: "23", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 124, label: "24", rowLabel: "E", visible: true, tierId: 1 },
  { seatId: 125, label: "25", rowLabel: "E", visible: true, tierId: 1 },
  {
    seatId: 1006,
    label: "E",
    rowLabel: "E",
    visible: true,
    tierId: 0,
  },
  //   6

  { seatId: 126, label: "1", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 127, label: "2", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 128, label: "3", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 129, label: "4", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 130, label: "5", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 131, label: "6", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 132, label: "7", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 133, label: "8", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 134, label: "9", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 135, label: "10", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 136, label: "11", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 137, label: "12", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 138, label: "13", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 139, label: "14", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 140, label: "15", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 141, label: "16", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 142, label: "17", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 143, label: "18", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 144, label: "19", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 145, label: "20", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 146, label: "21", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 147, label: "22", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 148, label: "23", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 149, label: "24", rowLabel: "F", visible: true, tierId: 1 },
  { seatId: 150, label: "25", rowLabel: "F", visible: true, tierId: 1 },
  {
    seatId: 1005,
    label: "F",
    rowLabel: "F",
    visible: true,
    tierId: 0,
  },
  // break ---
  { seatId: -51, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -52, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -53, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -54, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -55, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -56, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -57, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -58, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -59, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -60, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -61, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -62, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -63, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -64, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -65, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -66, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -67, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -68, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -69, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -70, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -71, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -72, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -73, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -74, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -75, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  { seatId: -76, label: "-", rowLabel: "F", visible: true, tierId: -1 },
  //   7

  { seatId: 151, label: "1", rowLabel: "G", visible: true, tierId: 1 },
  { seatId: 152, label: "2", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 153, label: "3", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 154, label: "4", rowLabel: "G", visible: false, tierId: 2 },
  { seatId: 155, label: "5", rowLabel: "G", visible: false, tierId: 2 },
  { seatId: 156, label: "6", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 157, label: "7", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 158, label: "8", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 159, label: "9", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 160, label: "10", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 161, label: "11", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 162, label: "12", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 163, label: "13", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 164, label: "14", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 165, label: "15", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 166, label: "16", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 167, label: "17", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 168, label: "18", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 169, label: "19", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 170, label: "20", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 171, label: "21", rowLabel: "G", visible: false, tierId: 2 },
  { seatId: 172, label: "22", rowLabel: "G", visible: false, tierId: 2 },
  { seatId: 173, label: "23", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 174, label: "24", rowLabel: "G", visible: true, tierId: 2 },
  { seatId: 175, label: "25", rowLabel: "G", visible: true, tierId: 2 },
  {
    seatId: 1004,
    label: "G",
    rowLabel: "G",
    visible: true,
    tierId: 0,
  },
  //   8

  { seatId: 176, label: "1", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 177, label: "2", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 178, label: "3", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 179, label: "4", rowLabel: "H", visible: false, tierId: 2 },
  { seatId: 180, label: "5", rowLabel: "H", visible: false, tierId: 2 },
  { seatId: 181, label: "6", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 182, label: "7", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 183, label: "8", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 184, label: "9", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 185, label: "10", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 186, label: "11", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 187, label: "12", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 188, label: "13", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 189, label: "14", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 190, label: "15", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 191, label: "16", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 192, label: "17", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 193, label: "18", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 194, label: "19", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 195, label: "20", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 196, label: "21", rowLabel: "H", visible: false, tierId: 2 },
  { seatId: 197, label: "22", rowLabel: "H", visible: false, tierId: 2 },
  { seatId: 198, label: "23", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 199, label: "24", rowLabel: "H", visible: true, tierId: 2 },
  { seatId: 200, label: "25", rowLabel: "H", visible: true, tierId: 2 },
  {
    seatId: 1003,
    label: "H",
    rowLabel: "H",
    visible: true,
    tierId: 0,
  },
  //   9

  { seatId: 201, label: "1", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 202, label: "2", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 203, label: "3", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 204, label: "4", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 205, label: "5", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 206, label: "6", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 207, label: "7", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 208, label: "8", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 209, label: "9", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 210, label: "10", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 211, label: "11", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 212, label: "12", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 213, label: "13", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 214, label: "14", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 215, label: "15", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 216, label: "16", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 217, label: "17", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 218, label: "18", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 219, label: "19", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 220, label: "20", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 221, label: "21", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 222, label: "22", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 223, label: "23", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 224, label: "24", rowLabel: "I", visible: true, tierId: 2 },
  { seatId: 225, label: "25", rowLabel: "I", visible: true, tierId: 2 },
  {
    seatId: 1002,
    label: "I",
    rowLabel: "I",
    visible: true,
    tierId: 0,
  },
  //   10

  { seatId: 226, label: "1", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 227, label: "2", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 228, label: "3", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 229, label: "4", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 230, label: "5", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 231, label: "6", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 232, label: "7", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 233, label: "8", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 234, label: "9", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 235, label: "10", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 236, label: "11", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 237, label: "12", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 238, label: "13", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 239, label: "14", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 240, label: "15", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 241, label: "16", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 242, label: "17", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 243, label: "18", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 244, label: "19", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 245, label: "20", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 246, label: "21", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 247, label: "22", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 248, label: "23", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 249, label: "24", rowLabel: "J", visible: true, tierId: 2 },
  { seatId: 250, label: "25", rowLabel: "J", visible: true, tierId: 2 },
  {
    seatId: 1001,
    label: "J",
    rowLabel: "J",
    visible: true,
    tierId: 0,
  },
  // break ---
  { seatId: 251, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 252, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 253, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 254, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 255, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 256, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 257, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 258, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 259, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 260, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 261, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 262, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 263, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 264, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 265, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 266, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 267, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 268, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 269, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 270, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 271, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 272, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 273, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 274, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 275, label: "-", rowLabel: "E", visible: true, tierId: -1 },
  { seatId: 276, label: "-", rowLabel: "E", visible: true, tierId: -1 },
];

export const priceTiers: Tier[] = [
  { tierId: -1, tierLabel: "", price: 0 }, // TIER BREAK
  { tierId: 0, tierLabel: "silver", price: 100 },
  { tierId: 1, tierLabel: "gold", price: 150 },
  { tierId: 2, tierLabel: "platinum", price: 200 },
];
